### ISSUE TITLE
Add word embeddings

### ISSUE THREAD

**Issue by skystrife** [meta-toolkit/meta#124]
In particular, the [GloVe](http://nlp.stanford.edu/projects/glove/) method looks promising and not too difficult to implement. We might even be able to reuse `learn::sgd_model` directly.

**Comment by smassung** [comment]
Once we have word embeddings, it would be great to have a bag-of-embedded-words analyzer. Doing similarity/indexing on these will take some thinking to incorporate into the MeTA framework.

**Comment by skystrife** [comment]
Fixed as of 184e7b0309181f01f05361b52d9e5dcadc47d79e.
