### ISSUE TITLE
running profile program

### ISSUE THREAD

**Issue by domarps** [meta-toolkit/meta#126]
The profile command is unable to identify non-existent files and outputs an empty file with filename suffixed with [OPTION].  For instance, consider a fictitious file, foo.txt .

`./profile config.toml foo.txt --stem`

outputs 

`Running stemming algorithm
 -> file saved as foo.stems.txt`

**Comment by smassung** [comment]
I suppose it would be reasonable to check if the file exists. You can do this with a call to `filesystem::file_exists()` at the beginning of `main`. If you'd like to make a pull request I will merge it.

**Comment by smassung** [comment]
Hi @domarps, if you don't want to make the change I will take care of it and we can have it out in v2.0.1.
