### ISSUE TITLE
Model files attached to v2.0.1 released require zlib

### ISSUE THREAD

**Issue by smassung** [meta-toolkit/meta#130]
Some parts of the model files are compressed with zlib, so MeTA users without zlib support can't use them (unless they decompress the files themselves).

Should we just make zlib required? Is it really that much of a dependency to support compressed corpora and model files?

**Comment by skystrife** [comment]
Yes, I see no real reason for not requiring zlib at this point. It is a small dependency which is pretty much ubiquitous.

**Comment by smassung** [comment]
Sounds good. I'll remove this as an optional dependency.

**Comment by skystrife** [comment]
We should update the setup guides on the website and in the readme to install zlib, too. I would vote for immediately updating the readme, but not the code, in the master branch.

**Comment by smassung** [comment]
Sure. I have this in a zlib branch to potentially merge into develop. We can have this as a required dependency in the next release.
