### ISSUE TITLE
option to output query results in trec_eval format

### ISSUE THREAD

**Issue by smassung** [meta-toolkit/meta#141]
This enables easy eval of TREC datasets using the official scorer.

More info [here](http://trec.nist.gov/trec_eval/).

This will also allow us to sanity check our own `ir_eval`.

**Comment by skystrife** [comment]
@smassung: don't we have code for this (or something like it) from the ACL paper?

**Comment by smassung** [comment]
Yes, I just modified a few lines of `query-runner` -- I could add an option for output format.

**Comment by smassung** [comment]
added in 17cc47527704d711e3a7edf5dbc6b7f3e06965a8
