### ISSUE TITLE
Setup Guide: Ubuntu 14.04

### ISSUE THREAD

**Issue by RyanNHG** [meta-toolkit/meta#142]
I recently installed meta on a new Docker image of Ubuntu 14.04.

The installation guide found at [meta-toolkit.org](https://meta-toolkit.org/setup-guide.html#ubuntu-build-guide) worked great until I tried to run __`cmake ../ -DCMAKE_BUILD_TYPE=Release`__

I received an error saying __`No CMAKE_CXX_COMPILER could be found.`__ 

The fix was very easy. It turns out that __`g++`__ is not installed on the standard ubuntu image.

I would recommend changing the install dependency step from __`sudo apt-get install cmake libicu-dev git libjemalloc-dev zlib1g-dev`__ to __`sudo apt-get install cmake libicu-dev git libjemalloc-dev zlib1g-dev g++`__ to make sure nobody runs into this issue again.

Just a heads up, keep up the good work!

**Comment by skystrife** [comment]
Thanks! This is fixed on the `develop` branch now. We'll be merging and tagging a new release here in a couple of days.

It's also fixed on the website.
