### ISSUE TITLE
Install as Library

### ISSUE THREAD

**Issue by wdavilaneto** [meta-toolkit/meta#143]
I think it is time to a mature toolkit as this to be installed as Library.

The main goal is to let developer to create an brand new project (CMake) linking Meta as Library and start to consume it's API.

Best Regards

**Comment by skystrife** [comment]
I *think* this is working as of 9a47a1b8e5d0a699098a097113d50b7123d08f61. I've only done some rudimentary testing (on Linux), but it seems to be working for me.

To consume the installed CMake configs for MeTA, you'll also need to install cpptoml from here: https://github.com/skystrife/cpptoml

But your standard `make install` should do the trick now! You can then use MeTA from CMake just like most other config-based packages:

```cmake
find_package(MeTA 2.4 REQUIRED)

add_executable(my-program src/my_program.cpp)
target_link_libraries(my-program meta-index) # or whatever other libs you need from MeTA
```
