### ISSUE TITLE
While installing in ubuntu 14.04

### ISSUE THREAD

**Issue by judeaugustinej** [meta-toolkit/meta#144]
devstack@openstack:~/Desktop/meta/build$ cmake ../ -DCMAKE_BUILD_TYPE=Release
CMake Error at CMakeLists.txt:18 (include):
  include could not find load file:

    deps/meta-cmake/FindOrBuildICU.cmake

CMake Error at CMakeLists.txt:19 (include):
  include could not find load file:

    deps/meta-cmake/SetClangOptions.cmake

CMake Error at CMakeLists.txt:20 (include):
  include could not find load file:

    deps/meta-cmake/CompilerKludges.cmake

CMake Error at CMakeLists.txt:43 (FindOrBuildICU):
  Unknown CMake command "FindOrBuildICU".

-- Configuring incomplete, errors occurred!
See also "/home/devstack/Desktop/meta/build/CMakeFiles/CMakeOutput.log".
See also "/home/devstack/Desktop/meta/build/CMakeFiles/CMakeError.log".

**Comment by smassung** [comment]
did you run `git submodule update --init --recursive`while following the setup guide?
