### ISSUE TITLE
Recreate feature selection with the current indexes

### ISSUE THREAD

**Issue by smassung** [meta-toolkit/meta#15]
Will need to discuss how we want this implemented.

* Need to take into account large datasets, unlike the previous version
* Runtime feature selection or index-creation time?

**Comment by skystrife** [comment]
Do we want this for 2.0?

**Comment by smassung** [comment]
I'd really like to merge the language-model branch so it doesn't die. It contains (obviously) a language model and the feature selection.

The feature selection should easily integrate with the indexes and support large datasets. The language model is more exploratory and would most likely need to be finalized in order to support large experiments. Is that ok with you if the language model is in this state? If we'd prefer not to include it, I can pull out only the feature selection for 2.0.

All this is contingent on me having enough time to actually do this though... if need be, it could be released in 2.1.

**Comment by smassung** [comment]
merged in #107
