### ISSUE TITLE
Populating inverted index from database

### ISSUE THREAD

**Issue by gabrielelanaro** [meta-toolkit/meta#153]
Hi, as far as the examples go, the corpus is usually stored in files and can be loaded using ``make_index(cfg)``. I was wondering if it is possible to create a corpus for example from a database or by adding documents incrementally

**Comment by skystrife** [comment]
It should be possible to create a corpus from an SQL database, but there isn't code currently written to do so. It wouldn't be too hard to write, though. It's just a matter of creating a new subclass of [corpus](https://meta-toolkit.org/doxygen/classmeta_1_1corpus_1_1corpus.html) that defines `has_next()`, `next()` and `size()` by calling into whatever SQL library you happen to have for C++. Your `sql_corpus` would just keep its SQL query iterator around, bumping it forward and extracting data on calls to `next()`.

To give you an idea, here's the business part of one of the simpler `corpus` classes: https://github.com/meta-toolkit/meta/blob/master/src/corpus/line_corpus.cpp#L19-L70

Once you have your corpus class, you would create an index using it like so:

```cpp
sql_corpus corpus{/* whatever parameters you pass here to initialize it */};

auto idx = index::make_index(*config, corpus); // this uses your specific corpus
```

(An alternative way, of course, would be to dump the text into files and then just index using one of the existing corpus formats).

As far as incremental indexing goes, that's a whole other beast. We currently don't support adding documents to an existing index. We want to do this eventually, but it's not currently in the works.

**Comment by gabrielelanaro** [comment]
Thanks for answering my question! Extending the corpus class sounds like a good solution, and I hope to see incremental indexing in the future.
Keep up the good work!
