### ISSUE TITLE
deprecate doc_{name,path}

### ISSUE THREAD

**Issue by smassung** [meta-toolkit/meta#168]
It is confusing and redundant since metadata stores these fields.

See original discussion here: https://forum.meta-toolkit.org/t/how-to-get-the-doc-title-in-string-format/169

**Comment by smassung** [comment]
Added to v3.0 since this is a major API change.

**Comment by skystrife** [comment]
We might be able to use something like this: https://github.com/pybind/pybind11/blob/5699986d125d772d2985418b7f948d23e93187df/include/pybind11/common.h#L33-L41

This makes calling the function produce a compiler warning (but not error). We can then remove the functions in their entirety in a future release.
