### ISSUE TITLE
How to parse data from a text message ?

### ISSUE THREAD

**Issue by Shravan40** [meta-toolkit/meta#176]
I would like to fetch all possible information from a text message. Can someone please suggest which algorithm to use ?.

For Example 1 : If the text message is "Dear Customer, You have made a Debit Card purchase of INR 962.00 on 26 Oct. Info.VPS*Brown House. Your Net Available Balance is INR 584.58."

Card Type : Debit
Transaction type : purchase
Spend Currency : INR
Spend Amount : 962.00
Merchant's Name : Brown House.
Balance Currency : INR
Balance Amount : 584.58

Example 2 : If the text message is "Txn of INR 535 made on Kotak Debit card XX3688 on 09-11-2016 23:13:57 at Namdhari Agro Fresh.Combined balance in A/c XX4827 is INR 3903"

Card Type : Debit
Transaction type : Txn
Spend Currency : INR
Spend Amount : 535
Merchant's Name : Namdhari Agro Fresh
Account Number :  XX4827
Balance Currency : INR
Balance Amount : 3903

P.S : I have very limited knowledge of NLP.

**Comment by skystrife** [comment]
Are these text messages machine generated? As in, are they always going to follow certain patterns? If so, you can probably just get away with using a regular expression (see http://regexr.com/ for some examples).

**Comment by Shravan40** [comment]
@skystrife : Yes these messages are machine generated. And yes they do follow the certain pattern but varies whenever sender changes. But all senders try to convey the same message.

**Comment by Shravan40** [comment]
@skystrife : Could you please suggest something better than regex ?

**Comment by skystrife** [comment]
95% sure that you could get most of the way there with just a regular expression (or a series of regular expressions), but if you want to feel more "academic" I guess you can get more complicated.

An alternative approach would be to do some kind of sequence modeling using e.g. a conditional random field. This is essentially the field of [information extraction](https://en.wikipedia.org/wiki/Information_extraction).
