### ISSUE TITLE
Error during the make command

### ISSUE THREAD

**Issue by aalind0** [meta-toolkit/meta#180]
During the 1% stage of the make command, I am getting the following errors:

> CMake Error at ExternalICU-stamp/download-ExternalICU.cmake:27 (message):
  error: downloading
  'http://download.icu-project.org/files/icu4c/58.2/icu4c-58_2-src.tgz'
  failed
>  .......
> CMakeFiles/ExternalICU.dir/build.make:89: recipe for target 'deps/icu-58.2/src/ExternalICU-stamp/ExternalICU-download' failed
make[2]: *** [deps/icu-58.2/src/ExternalICU-stamp/ExternalICU-download] Error 1
CMakeFiles/Makefile2:131: recipe for target 'CMakeFiles/ExternalICU.dir/all' failed
make[1]: *** [CMakeFiles/ExternalICU.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

I am using Ubuntu 16.04.

**Comment by Kanika91** [comment]
Hi,

I'm getting the same error. Could you elaborate on how you resolved it?

**Comment by chinmayee95** [comment]
Hello,
I am also facing the same error. Have you figured out how to resolve the issue?
