### ISSUE TITLE
Investigate support for spaces in path names for the config file and file corpus list

### ISSUE THREAD

**Issue by smassung** [meta-toolkit/meta#41]

**Comment by smassung** [comment]
@skystrife - the best fix I can see for this is to have an optional corpus.labels file like `line_corpus` does. I think it would be impossible to tell what is 1) a space in a filename vs 2) a label, aside from processing the entire file and making an educated guess.

Of course, the downside to this is that the corpus format will change (though not too significantly), and it will not be backwards compatible. What do you think?

**Comment by skystrife** [comment]
What's wrong with requiring a label for each line (e.g. "[none] path/to/file")? I feel like any issue with "path/to/file" containing spaces should be easily worked around (the filename is everything after the first whitespace delimited token until a newline). That should be a backwards-compatible change that could be released as a x.y.z bugfix.

That being said, I don't have any issue with just adding a labels file as a workaround. That more naturally supports not having labels anyway.

**Comment by smassung** [comment]
Yeah, I'll just update the documentation for `file_corpus` that a label is required. That makes more sense. My comment from May 5th 2014 about spaces not working in filenames is incorrect (just tested now), I think that was not assuming a label is required.

**Comment by smassung** [comment]
updated in de40b1f0fbd42cbb4a552701574bd66ffceecd76
