### ISSUE TITLE
feature scaling for classifiers

### ISSUE THREAD

**Issue by smassung** [meta-toolkit/meta#45]
Option to scale feature vectors in a predefined range (e.g. [0,1]). This should reduce SGD's convergence rate as well as make distance calculations proportional.

**Comment by skystrife** [comment]
This is addressed with using the Normalized Adaptive Gradient algorithm in our sgd implementation as of 69f42f8, which should make the algorithm feature-scale invariant (or at least significantly less sensitive).

...unless this is for things beyond SGD, in which case maybe we should have a separate issue.
