### ISSUE TITLE
Add ability to load classifiers from model files

### ISSUE THREAD

**Issue by skystrife** [meta-toolkit/meta#48]
Currently some of the classifiers save model files (like `sgd`), but they don't have a way of initializing from a pre-trained model. For sgd specifically, the constructor calls `reset()` immediately.

We should add another constructor that allows for loading a pre-trained classifier from its model file. We'll need to change the way that the model file is stored most likely, but this should be a relatively easy change (for `sgd` anyway).

**Comment by smassung** [comment]
Added in #114
