### ISSUE TITLE
Check for malformed index on load?

### ISSUE THREAD

**Issue by skystrife** [meta-toolkit/meta#54]
Right now, if the index structure was created (I think all it takes is for the folder to exist?) but not finished, you get an exception thrown about not being able to open the postings file for the index.

This is programmatically fine, but maybe we should be doing something on that exception in the example applications (such as just forcing a re-indexing)?

**Comment by smassung** [comment]
Fixed in 3404d89e2a135ae3322569acedfb149b53010c2a

Index files are checked at load time to make sure they all exist. This doesn't check if they're  corrupt, because that would be too expensive to check at each load time (and potentially not even possible to tell).
