### ISSUE TITLE
Document metadata storage/retrieval

### ISSUE THREAD

**Issue by skystrife** [meta-toolkit/meta#56]
Currently we have an ad-hoc system in place for keeping track of a few pieces of document metadata that are in some sense "extras" from an indexing perspective:

- Class labels
- Paths (when indexing a `file_corpus`)
- Names

It would be nice to have a more flexible document metadata storage system that allows storing more arbitrary data with each document, indexed by its id.

The main use case I'm thinking of right now would be flexibility in defining search filters: if we have nice ways to store things like rating data, location, product ids, etc. we can more readily support facet search.

**Comment by smassung** [comment]
added in a75f909e8da85f35f80a211317af1f3e29f1ae8e
