### ISSUE TITLE
Demo app

### ISSUE THREAD

**Issue by smassung** [meta-toolkit/meta#57]
Create demo app that showcases low-level MeTA functionality like tokenization, POS-tagging, stemming, frequency counting, etc. It should be easily modified by the user to experiment with settings.

No dataset should be necessary, just use a single text file as input and perform all analysis on that.

**Comment by skystrife** [comment]
Can the profile branch be merged to close this?

**Comment by smassung** [comment]
I think so. The toml changes will need to be applied here (and I just realized the tutorials still have the old toml group instead of table lingo).

What was the consensus on the creation of the `blank_filter`? Necessary due to the way ICU processes things?

**Comment by smassung** [comment]
I'd also like to write a tutorial for how to use `./profile` but that can be a separate issue.

**Comment by skystrife** [comment]
The docs can be updated but only in a separate branch since we have people using master right now don't we? That branch should be merged into gh-pages when develop is merged for v1.3.

I think I fixed the icu tokenizer bug (in develop) so blank filter should be unnecessary now.

**Comment by smassung** [comment]
Ok, I will merge develop into profile and see if I can get rid of `blank_filter`.

**Comment by skystrife** [comment]
Is it worth adding the parser to that app?

**Comment by smassung** [comment]
I think it would be. I just committed the changes to the profile branch. Would you like to add the parser to it?

**Comment by skystrife** [comment]
Sure.

**Comment by skystrife** [comment]
Merged as of d8df01b.
