### ISSUE TITLE
Modify tokenizer or add filter for Penn Treebank normalization 

### ISSUE THREAD

**Issue by skystrife** [meta-toolkit/meta#59]
E.g., -LRB-, -RRB-, do n't (two tokens), and probably others I'm forgetting.

This will help the POS tagger and the parser correctness on raw input data.

**Comment by skystrife** [comment]
@smassung can you think of other things I'm forgetting, besides punctuation?

**Comment by smassung** [comment]
Don't they have all quotes translated to `` and '' ?

**Comment by skystrife** [comment]
Yeah.

I'm thinking this should be a separate filter rather than a modification of a tokenizer. What do you think?

**Comment by smassung** [comment]
Separate filter makes sense.

**Comment by skystrife** [comment]
Just added this.

I didn't make it part of the default filter chain since I'm not convinced it's actually helpful there. It's mainly to be used with the POS and (future) tree analyzers.
