### ISSUE TITLE
Update docs for v1.3

### ISSUE THREAD

**Issue by skystrife** [meta-toolkit/meta#68]
This includes the tutorials on the website as well as regenerating the doxygen (and fixing the weird N problem that it currently has...)

**Comment by skystrife** [comment]
Checklist for myself:

- [x] Regenerate Doxygen
- [x] Update existing tutorials
- [ ] Tutorial for POS tagging (both the CRF and the greedy perceptron tagger)
- [ ] Tutorial for parsing
- [ ] Tutorial for `profile` (maybe put this right after the system overview?)
- [ ] Merge `gh-pages-develop` branch into `gh-pages`

**Comment by smassung** [comment]
Is the link in the footer of each page supposed to go to the doxygen? Right now it goes to the github page.

**Comment by skystrife** [comment]
It's supposed to go to the repo, but we can change it to go to the Doxygen if you think that is less confusing.

I read it as "this website is the documentation for <the MeTA toolkit>".
