### ISSUE TITLE
Create a severity level for logger that writes to a log file

### ISSUE THREAD

**Issue by smassung** [meta-toolkit/meta#78]
This way we can have some persistent logging. Maybe even name files with a timestamp so they aren't overwritten, or append to a file if it exists already.

**Comment by skystrife** [comment]
This can already be done with the existing logger. You just need to add a file-based sink in the same style as is done for `cerr` in `set_cerr_logging()`. You can pick what levels you want in the file when you add the sink, so you could say something like "only info and above in severity get logged to the file".

**Comment by smassung** [comment]
Oh I see, thanks. I misunderstood the logger class!
