### ISSUE TITLE
Document all factory methods with accepted TOML configuration fields

### ISSUE THREAD

**Issue by skystrife** [meta-toolkit/meta#91]
See: https://forum.meta-toolkit.org/t/list-filter-how-to-specify-list-location/32

We should have an explanation of the configurable fields for everything we're creating based on config files, so people don't have to look at the source code to understand what things to pass e.g. a filter if it's not mentioned in a tutorial already.

**Comment by smassung** [comment]
I documented analyzer-related things, which is a start. Doxygen will still have to be regenerated of course.
