### ISSUE TITLE
 Problem with MeTA Installation on Ubuntu 14.04.2 LTS

### ISSUE THREAD

**Issue by IbrahimIbrahim** [meta-toolkit/meta#97]
cmake ../ -DCMAKE_BUILD_TYPE=ReleaseCMake Error at CMakeLists.txt:19 (find_package):
  By not providing "FindICU.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ICU", but
  CMake did not find one.
  Could not find a package configuration file provided by "ICU" with any of
  the following names:
    ICUConfig.cmake
    icu-config.cmake

**Comment by skystrife** [comment]
Make sure you've done all of the steps mentioned in [the relevant setup guide for Ubuntu 14.04](https://meta-toolkit.org/setup-guide.html#ubuntu-1404-lts-build-guide). In particular, it looks like you forgot this step:

```bash
git submodule update --init --recursive
```

**Comment by IbrahimIbrahim** [comment]
I've really gone through all the steps, but in our class' assignment we have one extra step, which is: "git reset --hard v1.3.6", and I am not sure if this might have affected the flow of the installation!
Anyway, I have repeated the steps and now after "cmake ../ -DCMAKE_BUILD_TYPE=Release", I get:
 
-- Performing Test HAS_CXX14
-- Performing Test HAS_CXX14 - Failed
-- Performing Test HAS_CXX1Y
-- Performing Test HAS_CXX1Y - Success
-- Compiler supports C++1y (using it)
-- Performing Test META_HAS_STD_SHARED_PTR_ATOMICS
-- Performing Test META_HAS_STD_SHARED_PTR_ATOMICS - Failed
-- Performing Test META_HAS_STREAM_MOVE
-- Performing Test META_HAS_STREAM_MOVE - Failed
-- Performing Test META_HAS_STD_MAKE_UNIQUE
-- Performing Test META_HAS_STD_MAKE_UNIQUE - Failed
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Performing Test CPPTOML_HAS_STD_PUT_TIME
-- Performing Test CPPTOML_HAS_STD_PUT_TIME - Failed
-- Performing Test CPPTOML_HAS_STD_REGEX
-- Performing Test CPPTOML_HAS_STD_REGEX - Failed
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done

**Comment by skystrife** [comment]
That output looks right---the last line is telling you that `cmake` successfully generated the `Makefile`s needed for building. Try running

```
make
```

to build the code, and then

```
ctest --output-on-failure
```

to make sure your unit tests are passing.

**Comment by IbrahimIbrahim** [comment]
93% tests passed, 1 tests failed out of 15, which is the rankers.

**Comment by skystrife** [comment]
Hmm... it's probably just that the machine is too slow for the timeouts we've set. Try changing `src/test/unit_tests.cmake` on line 38 to have a higher number, maybe like 85 or so and try again.

**Comment by IbrahimIbrahim** [comment]
Yes true, that would be the case over here since I am using Intel(R) Atom(TM) CPU N450@1.66GHz.
I was at least expecting to receive a test failure on test # 3 because of that, but sometimes I get that result, sometimes it surprisingly succeeds without throwing any errors!
Anyway, I have changed the time-out limit to 100 and it is still not enough, let me try with 1000 ..

**Comment by IbrahimIbrahim** [comment]
100% tests passed, 0 tests failed out of 15
Voila!

Rankers were fixed by changing the time-out period to 100.
should I worry about my future MeTA projects using this Atom processor ?

**Comment by skystrife** [comment]
No, I think you should be fine seeing as the issue was only that the tests took longer to complete. It seems like the outputs are still matching just fine, they just take a bit longer to complete.

If you happen to have a more powerful machine available, MeTA will make good use of it, but if you don't it should still be able to run fine on that machine.

**Comment by IbrahimIbrahim** [comment]
During my future usage of MeTA and the applications I will be developing, I might somehow eventually add up to the experience of testing it over this processor; this will help us investigate MeTA's Portability. I wish I will embark upon the opportunity in understanding its code some day too!
thank you so much for your efforts and consistent support!
Best wishes,
